name: OSV-Scanner
description: Run osv-scanner-action recursively in the current directory.

runs:
  using: composite
  steps:
    - name: Scan on push
      if: ${{ github.event_name == 'push' }}
      uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@05957d45c705b7779285f099a80dd9b9002cea6b" # v1.9.2
      with:
        scan-args: |-
          -r
          ./
    - name: Scan on PR
      if: ${{ github.event_name == 'pull_request' }}
      uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@05957d45c705b7779285f099a80dd9b9002cea6b" # v1.9.2
      with:
        scan-args: |-
          -r
          ./
