name: OSV-Scanner
description: Run osv-scanner-action recursively in the current directory.

runs:
  using: composite
  steps:
    - name: Scan on push
      if: ${{ github.event_name == 'push' }}
      uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@d15851b0a21e3d716c10c66f72b2cae1384a6f7e" # v1.9.2
      with:
        scan-args: |-
          -r
          ./
    - name: Scan on PR
      if: ${{ github.event_name == 'pull_request' }}
      uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@d15851b0a21e3d716c10c66f72b2cae1384a6f7e" # v1.9.2
      with:
        scan-args: |-
          -r
          ./
