name: Formatting
description: Uses CLANG to format C source and header files

inputs:
  sourcePaths:
    description: 'Paths with source files, separated by spaces'
    required: true
    default: ''

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2
      - name: Verify formatting
        run: |
          SOURCE_PATHS="${{ inputs.sourcePaths }}"
          ./format-source.sh check
