name: Run go generate and report changes
description: Run go generate from the current directory and report any changes. It supposes go is already installed.

inputs:
  working-directory:
    description: Directory were to run the action. All other paths are relative to this one.
    default: '.'
  tools-directory:
    description: Directory pointing to go.mod file for checking tool versionning. If none is provided, it will download latest.
  paths-to-ignore:
    description: Files and paths to ignore when checking if generated files changed. This is passed to git update-index.
    default: po/* doc/*.md README.md
  generate-diff-regexp-to-ignore:
    description: Files and paths to ignore when checking if generated files changed. This is passed to diff -I.
    default: "^//.*protoc.*v"
  fail-on-diff:
    description: Fail the job on any detected diff.
    default: "true"
outputs:
  diff:
    description: Returns if there is a local diff.
    value: ${{ steps.go-generate-check.outputs.diff }}

runs:
  using: "composite"
  steps:
    - name: Install tools and dependencies
      id: proto-deps
      working-directory: ${{ inputs.tools-directory }}
      run: |
        echo "::group::Install tools and dependencies"
        set -eu

        tools=$(grep -o '_ ".*"' *.go | cut -d '"' -f 2)

        needsProtoc=false
        for tool in ${tools}; do
          if [[ "${tool}" == *protoc* ]]; then
            echo "needs-protoc=true" >> $GITHUB_OUTPUT
          fi
          go install ${tool}
        done

        echo "::endgroup::"
      shell: bash
    - name: Install latest protoc
      uses: arduino/setup-protoc@v2
      if: ${{ steps.proto-deps.outputs.needs-protoc == 'true' }}
    - name: Regenerate files with go generate
      id: go-generate-run
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo Regenerate files with go generate
        set -eu

        go generate ./...
      shell: bash
    - name: Ensure there is no diff between current and generated files
      if: ${{ always() && steps.go-generate-run.outcome == 'success' }}
      id: go-generate-check
      # https://github.com/orgs/community/discussions/25246
      uses: canonical/desktop-engineering/gh-actions/common/has-diff@main
      with:
        working-directory: ${{ inputs.working-directory }}
        paths-to-ignore: ${{ inputs.paths-to-ignore }}
        regexp-to-ignore: ${{ inputs.generate-diff-regexp-to-ignore }}
        fail-on-diff: ${{ inputs.fail-on-diff }}
