name: Comprehensive Flutter actions

on:
  workflow_call:
    inputs:
      flutter-version:
        description: The Flutter version to use for this workflow (defaults to FVM version)
        type: string
      os:
        description: OS to run on
        type: string
        default: ubuntu-latest

jobs:
  analyze:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./gh-actions/flutter/setup
        with:
          flutter-version: ${{ inputs.flutter-version }}
      - run: fvm dart analyze

  format:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./gh-actions/flutter/setup
        with:
          flutter-version: ${{ inputs.flutter-version }}
      - run: fvm dart format .

  test:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./gh-actions/flutter/setup
        with:
          flutter-version: ${{ inputs.flutter-version }}
      - run: fvm flutter test
