name: Install gotestfmt and our wrapper script
description: Install gotestfmt and our wrapper script which improves the output and copies it to log files

inputs:
  tools-directory:
    description: Directory pointing to go.mod file for checking tool versioning. If none is provided, the latest version will be downloaded.

runs:
  using: "composite"
  steps:
    - name: Install gotestfmt
      working-directory: ${{ inputs.tools-directory }}
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        # Install gotestfmt
        echo "::group::Install gotestfmt"
        TOOL=github.com/ubuntu/gotestfmt/v2/cmd/gotestfmt
        VERSION=$(go mod edit --json | jq -r ".Require[] | select(.Path==\"${TOOL}\") | .Version" || true)

        if [ -z "${VERSION}" ]; then
          VERSION="latest"
        fi

        go install "${TOOL}@${VERSION}"
        echo "::endgroup::"

    - name: Install gotestfmt wrapper script
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        # Install gotestfmt wrapper script
        echo "::group::Install gotestfmt wrapper script"
        # We install the wrapper to a different directory to avoid conflicts
        # with the gotestfmt binary. We also add the directory to the PATH.
        # The wrapper script expects gotestfmt to be in $GOPATH/bin, where
        # go install puts it.
        DEST=${GITHUB_ACTION_PATH}/bin
        mkdir -p "${DEST}"
        install -m 755 "${GITHUB_ACTION_PATH}/gotestfmt" "${DEST}"
        echo "${DEST}" >> "${GITHUB_PATH}"
        echo "::endgroup::"
