name: Speed up dpkg package installation
description: Configures dpkg to exclude locales and manpages from installed packages, speeding up package installation.

runs:
  using: "composite"
  steps:
    - name: Exclude locales and manpages from dpkg
      id: exclude-locales-and-manpages
      shell: bash
      run: |
        DPKG_CFG_PATH=/etc/dpkg/dpkg.cfg.d/01-exclude-locales-and-manpages
        DPKG_EXCLUDES="path-exclude=/usr/share/locale/*
        path-exclude=/usr/share/man/*
        path-exclude=/usr/share/doc/*
        path-exclude=/usr/share/info/*"
        if [ "$(id -u)" -eq 0 ]; then
          echo "$DPKG_EXCLUDES" > "$DPKG_CFG_PATH"
        else
          echo "$DPKG_EXCLUDES" | sudo tee "$DPKG_CFG_PATH"
        fi
