name: Print summary
description: This prints the summary of any given step results in an array.

inputs:
  title:
    description: The title header of the summary section.
    required: true
  step-results:
    description: A new-line separate list of .outcome result of a job, followed by a space and then, the text to print next to the result.
    required: true

runs:
  using: "composite"
  steps:
    - name: Print job summary
      shell: bash
      run: |
        # Print job summary
        set -eu

        print_status_line () {
          status=$1

          icon=":question:"
          if [ "${status}" == "success" ]; then
            icon=":green_circle:"
          elif [ "${status}" == "failure" ]; then
            icon=":red_circle:"
          elif [ "${status}" == "skipped" ]; then
            icon=":white_circle:"
          fi

          echo "| $2 | ${icon} |" >> $GITHUB_STEP_SUMMARY
        }

        echo '### ${{ inputs.title }}' >> $GITHUB_STEP_SUMMARY

        echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
        echo "| --- | :---:  |" >> $GITHUB_STEP_SUMMARY

        while IFS= read -r jobResult; do
            # Trim leading and trailing whitespaces
            shopt -s extglob
            jobResult="${jobResult##*( )}"
            jobResult="${jobResult%%*( )}"
            shopt -u extglob

            if [ -z "${jobResult}" ]; then
              continue
            fi

            res=${jobResult%%" "*}
            name=${jobResult#*" "}
            print_status_line "${res}" "${name}"
        done <<< '${{ inputs.step-results }}'
