name: Has diff
description: Returns if there is diff within the repository from the current directory.

inputs:
  working-directory:
    description: Directory were to run the action. All other paths are relative to this one.
    default: '.'
  regexp-to-ignore:
    description: Regexp patterns passed to ignore-matching-lines when diffing.
  paths-to-ignore:
    description: Files and paths to ignore when checking if they changed. This is passed to git update-index.
  fail-on-diff:
    description: Fail the job on any detected diff.
    default: "false"
outputs:
  diff:
    description: Returns if there is a local diff.
    value: ${{ steps.has-diff.outputs.diff }}

runs:
  using: "composite"
  steps:
    - name: Returns if there is a local diff
      id: has-diff
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo Returns if there is a local diff
        set -eu

        # Ignore requested file for changes
        if [ -n '${{ inputs.paths-to-ignore }}' ]; then
          files_to_ignore=$(ls ${{ inputs.paths-to-ignore }} 2>/dev/null || true)
          if [ -n "${files_to_ignore}" ]; then
            git update-index --assume-unchanged ${files_to_ignore}
            on_exit() {
                # Restore files
                git update-index --no-assume-unchanged ${files_to_ignore}
            }
            trap on_exit EXIT INT QUIT ABRT PIPE TERM
          fi
        fi


        # Any new file needs to be considered as empty.
        git add -N .

        # Ignore modification time which will change anyway due to git checkout.
        diffCmd="diff --ignore-matching-lines 'modTime'"

        # Additional arguments to ignore.
        if [ -n "${{ inputs.regexp-to-ignore }}" ]; then
          regexp_to_ignore='${{ inputs.regexp-to-ignore }}'
          diffCmd="${diffCmd} --ignore-matching-lines ${regexp_to_ignore}"
        fi

        DIFF=$(git difftool -y -x "${diffCmd}" .)
        if [ -z "${DIFF}" ]; then
          echo "diff=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        echo "diff=true" >> $GITHUB_OUTPUT

        echo "A modification has been detected:"
        git status .

        echo ""
        echo "::group::Full unfiltered diff"
        git diff --ignore-cr-at-eol .
        echo "::endgroup::"

        if [ "${{ inputs.fail-on-diff }}" == true ]; then
          exit 1
        fi
