name: Golang code sanity check
description: Checks code against of our desktop Go code quality and process standards.

inputs:
  working-directory:
    description: Directory were to run the action. All other paths are relative to this one.
    default: "."
  go-build-script:
    description: For more complex build steps, pass the script directly to it (executed through bash). go-tags is then ignored for building.
  go-tags:
    description: A comma separate list of go tags to consider when linting, building and checking for vulnerabilities.
  tools-directory:
    description: Directory pointing to go.mod file for checking tool versioning. If none is provided, it will download latest.
  golangci-lint-configfile:
    description: Which config file to check for golangci-lint. If not set, it will look for .golangci-lint in your project, or default to desktop team defaults.
  generate-diff-paths-to-ignore:
    description: Files and paths to ignore when checking if generated files changed. This is passed to git update-index.
    default: po/* docs/**/*.md README.md
  token:
    description: A token to authenticate GH API calls with. It will be used to get the latest protoc release, for example. Make sure to limit the permissions, e.g. a zero-permissions token is acceptable.
    default: ""
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version-file: ${{ inputs.working-directory }}/go.mod
        check-latest: true
        cache: false
    - name: Install jq
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        # Install jq
        echo "::group::Install jq"

        if [ "${{runner.os}}" = "Windows" ]; then
          winget.exe install jqlang.jq --accept-source-agreements --accept-package-agreements --silent --verbose || true
        elif [ "${{ runner.os }}" = "macOS" ]; then
          # No setup needed for macOS
          :
        else
          sudo --version &> /dev/null && SUDO="sudo" || SUDO=""
          DEBIAN_FRONTEND=noninteractive $SUDO apt update
          DEBIAN_FRONTEND=noninteractive $SUDO apt install jq
        fi
        echo "::endgroup::"
        jq --version
    - name: Get tooling version
      id: tooling-version
      if: ${{ always() }}
      working-directory: ${{ inputs.tools-directory }}
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        # Get tooling version

        function set-version {
          name=$1
          path=$2
          version="latest"
          mod_version="$(
            go mod edit --json | jq -r ".Require[] | select(.Path==\"${path}\") | .Version"
          )"
          if [ -n "${mod_version}" ]; then
            version="${mod_version}"
          fi
          echo "${name}=${version}" >> $GITHUB_OUTPUT
        }

        set-version "golangci-lint" "github.com/golangci/golangci-lint/v2"
        set-version "vulncheck" "golang.org/x/vuln"
    - name: Get arguments and version for golangci-lint
      if: ${{ always() && steps.tooling-version.outcome == 'success' }}
      id: golanci-lint
      working-directory: ${{ inputs.working-directory }}
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        # Get arguments and version for golangci-lint

        # Detect which config file to use
        config='${{ github.action_path }}/.golangci-lint'
        if [ -f ".golangci-lint" ]; then
          config=".golangci-lint"
        fi
        if [ -n '${{ inputs.golangci-lint-configfile }}' ]; then
          echo "Using project local config file"
          config='${{ inputs.golangci-lint-configfile }}'
        fi
        args="--config ${config}"

        # Optional build tag go-tags
        tags='${{ inputs.go-tags }}'
        if [ -n "${tags}" ]; then
          args="${args} --build-tags=${tags}"
        fi
        echo "args=${args}" >> $GITHUB_OUTPUT

    - name: Code formatting, vet, static checker Security…
      if: ${{ always() && steps.golanci-lint.outcome == 'success' }}
      id: golangci-lint-check
      uses: golangci/golangci-lint-action@v9
      with:
        version: ${{ steps.tooling-version.outputs.golangci-lint }}
        args: ${{ steps.golanci-lint.outputs.args }}
        working-directory: ${{ inputs.working-directory }}

    - name: Update module files
      if: ${{ always() }}
      id: update-mod-files
      working-directory: ${{ inputs.working-directory }}
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        # go mod tidy
        echo "::group::go mod tidy"

        go mod tidy
        echo "::endgroup::"

    - name: Ensure there is no diff between current and generated go.mod and go.sum files
      if: ${{ always() && steps.update-mod-files.outcome == 'success' }}
      id: gomod-check
      # https://github.com/orgs/community/discussions/25246
      uses: canonical/desktop-engineering/gh-actions/common/has-diff@main
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Ensure there is no diff between current and generated files
      if: ${{ always() }}
      id: go-generate-check
      # https://github.com/orgs/community/discussions/25246
      uses: canonical/desktop-engineering/gh-actions/go/generate@main
      with:
        tools-directory: ${{ inputs.tools-directory }}
        paths-to-ignore: ${{ inputs.generate-diff-paths-to-ignore }}
        working-directory: ${{ inputs.working-directory }}
        token: ${{ inputs.token }}
    - name: Build any binaries
      if: ${{ always() }}
      id: build-check
      working-directory: ${{ inputs.working-directory }}
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        # go build
        echo "::group::go build"

        if [ -n '${{ inputs.go-build-script }}' ]; then
          buildTest=$(mktemp)
          cat > ${buildTest} <<SCRIPTEOF
            ${{ inputs.go-build-script }}
        SCRIPTEOF
          bash ${buildTest}
          exit 0
        fi

        tags='${{ inputs.go-tags }}'
        if [ -n "${tags}" ]; then
          tags="-tags=${tags}"
        fi

        go build ${tags} ./...
        echo "::endgroup::"

    - name: Install govulncheck
      if: ${{ always() && steps.tooling-version.outcome == 'success' }}
      id: install-govulncheck
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        # Install govulncheck
        echo "::group::Install govulncheck"
        GOTOOLCHAIN=$(go mod edit -json "${{ inputs.tools-directory }}/go.mod" | jq -r '.Toolchain')
        if [ "${GOTOOLCHAIN}" == "null" ]; then
          GOTOOLCHAIN="go$(go mod edit -json "${{ inputs.tools-directory }}/go.mod" | jq -r '.Go')"
        fi
        GOTOOLCHAIN=${GOTOOLCHAIN} \
          go install golang.org/x/vuln/cmd/govulncheck@${{ steps.tooling-version.outputs.vulncheck }}
        echo "::endgroup::"

    - name: Known vulnerabilities check
      if: ${{ always() && steps.install-govulncheck.outcome == 'success' }}
      id: vulnerabilities-check
      working-directory: ${{ inputs.working-directory }}
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        # govulncheck

        tags='${{ inputs.go-tags }}'
        if [ -n "${tags}" ]; then
          tags="-tags=${tags}"
        fi

        govulncheck -test ${tags} ./...

    - name: Compute title of summary
      if: ${{ always() }}
      id: compute-summary-title
      working-directory: ${{ inputs.working-directory }}
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        # Compute title of summary based on current directory

        title="Code sanity summary"

        workspace=${{ github.workspace }}
        dir=$(pwd)
        dir=${dir#"${workspace}"}
        if [ -n "${dir}" ]; then
          title="${title} on ${dir}"
        fi
        echo "title=${title}" >> $GITHUB_OUTPUT
    - name: Summary
      if: ${{ always() && steps.compute-summary-title.outcome == 'success' }}
      # https://github.com/orgs/community/discussions/25246
      uses: canonical/desktop-engineering/gh-actions/common/print-summary@main
      with:
        title: ${{ steps.compute-summary-title.outputs.title }}
        step-results: |
          ${{ steps.golangci-lint-check.outcome }} Linting
          ${{ steps.gomod-check.outcome }} Go module files up to date
          ${{ steps.go-generate-check.outcome }} Generated files up to date
          ${{ steps.build-check.outcome }} Build
          ${{ steps.vulnerabilities-check.outcome }} Vulnerability scanning
